---
title: "Project Proposal"
author: "Bruce R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Topic

<!-- Identify the subject of your project. What are you going to be making your visualizations about? -->

<!-- Some examples of possible topics: -->
<!-- * Educational achievement in a country/province/city -->
<!-- * Sports - player statistics and performance of a team -->
<!-- * Political survey data like what we've used in previous courses in this specialization -->
<!-- * Business data - prices, company performance, budget data, productivity data -->

<!-- Please indicate in as much detail as possible what the topic is going to be. -->

I will be looking at state tax revenue for all 50 states in the United States for the years 2005-2020. The tax data is broken down in to categories of its source. I'm interested in visualizing how each category of tax income, for example, property taxes, varies across states. I will also look at how an individual state's break down of category has changed, or not changed, over recent years.


## Data Sources

<!-- Please identify the source(s) of data you will use for your project. Provide links to websites and citations for the data. Who created these data? How were they collected? -->

The data was collected by the U.S. Census Bureau and the data is available from Census.gov website at the following url:

https://www.census.gov/programs-surveys/stc/data/datasets.2019.List_446124122.html 

The direct link to the data, code book, and other information is at this:
https://www2.census.gov/programs-surveys/stc/datasets/historical/STC_Historical_2020.zip

I will also use population estimates for the states for per capita calculations.

## Description of the Data

<!-- Please provide specific details about your data. -->

<!-- * If the data covers a timespan, what is the time period? -->
<!-- * If the data covers a geographical location, what geographical location(s)? -->
<!-- * If the data is about a business, political, or non-governmental entity or activity, which entities or activities does it cover? For example is the data about economics, schools, politics, sports, or something else? -->
<!-- * What characteristics are captured by the data? For example, if your data is about cities, what characteristics of the cities are captured in the data? Population, crime rates, economic measures, business activity, traffic? -->
<!-- * Assuming your data is rectangular (like a spreadsheet), how many rows and columns are in the dataset? If your data is not rectangular, how are you going to create a "tidy" dataset from these data? -->

The data actually goes back as far as 1902, but I will concentrate on the years from 2005 through 2020. I didn't want to look at all the data and, according to the documentation, significant changes to the classification system were made in 2005 so I decided to start there. The data is for all 50 states in the United States. It breaks down where the taxes comes from into categories, e.g., property taxes, Alcoholic Beverage Tax, licenses, etc. The amounts are given in thousands of dollars.


## Ideas about the figures that you will create to visualize this data:

<!-- Please provide ideas for the figures you are going to generate from these data. Are you going to make line plots, bar charts, density plot, dumbbell charts, choropleths, or what? You should provide a description of at least three figures. Your final project will include eight figures. -->

I plan to make interactive charts where states can be chosen to see the data for that state. The user will able to chose different graphs for each state.

I will make line charts to plot the changes over the time period. 
I will be making graphs to compare how states differ in the amount and source of their tax revenue.
I will make a chorpleth for the whole United States.

 Most graphs will be state based, but I will have a U.S. based density, histogram, or  box-plot graph for distribution of the taxes collected. I will facet or have multiple figures for each year.
 
